[package]
name = "ipchat"
version = "0.0.0"
edition = "2024"
description = "IP based Chat Solution for Local Network Communications"
keywords = ["chat", "wlan", "local", "ip"]
license = "MIT"
readme = "../../README.md"
categories = ["api-bindings"]

[lib]
name = "ipchat"
path = "src/lib.rs"

[[bin]]
name = "ipchat"
path = "src/bin/main.rs"

[dependencies]
axum = { workspace = true }
anyhow = { workspace = true }
chrono = { workspace = true, features = ["serde"] }
clap = { workspace = true, features = ["std", "derive", "env"] }
futures-util = { workspace = true }
http = { workspace = true }
if-addrs = { workspace = true }
local-ip-address = { workspace = true }
mime_guess = { workspace = true }
rust-embed = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
socket2 = { workspace = true }
tokio = { workspace = true, features = ["fs", "macros", "net", "rt", "rt-multi-thread", "signal", "sync", "time"] }
tokio-tungstenite = { workspace = true }
tower-http = { workspace = true, features = ["trace"] }
tracing-subscriber = { workspace = true, features = ["env-filter"] }
tracing = { workspace = true }
utoipa = { workspace = true, features = ["chrono", "macros", "uuid"] }
utoipa-swagger-ui = { workspace = true, features = ["axum"] }
uuid = { workspace = true, features = ["serde", "v4"] }
