[package]
name = "ipchat"
version = "0.0.0"
edition = "2024"
description = "IP based Chat Solution for Local Network Communications"
keywords = ["chat", "wlan", "local", "ip"]
license = "MIT"
readme = "../../README.md"
categories = ["api-bindings"]

[lib]
name = "ipchat"
path = "src/lib.rs"

[[bin]]
name = "ipchat"
path = "src/bin/main.rs"

[features]
default = ["server"]
server = [
    "dep:axum",
    "dep:clap",
    "dep:futures-util",
    "dep:http",
    "dep:if-addrs",
    "dep:local-ip-address",
    "dep:mime_guess",
    "dep:rust-embed",
    "dep:socket2",
    "dep:tokio",
    "dep:tokio-tungstenite",
    "dep:tower-http",
    "dep:tracing",
    "dep:tracing",
    "dep:tracing-subscriber",
    "dep:utoipa",
    "dep:utoipa-swagger-ui"
]

[dependencies]
anyhow = { workspace = true }
chrono = { workspace = true, features = ["serde"] }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
uuid = { workspace = true, features = ["serde", "v4"] }

# Optional dependencies
axum = { workspace = true, optional = true }
clap = { workspace = true, optional = true, features = ["std", "derive", "env"] }
futures-util = { workspace = true, optional = true }
http = { workspace = true, optional = true }
if-addrs = { workspace = true, optional = true }
local-ip-address = { workspace = true, optional = true }
mime_guess = { workspace = true, optional = true }
rust-embed = { workspace = true, optional = true }
socket2 = { workspace = true, optional = true }
tokio = { workspace = true, optional = true, features = ["fs", "macros", "net", "rt", "rt-multi-thread", "signal", "sync", "time"] }
tokio-tungstenite = { workspace = true, optional = true }
tower-http = { workspace = true, optional = true, features = ["cors", "trace"] }
tracing = { workspace = true, optional = true }
tracing-subscriber = { workspace = true, optional = true, features = ["env-filter"] }
utoipa = { workspace = true, optional = true, features = ["chrono", "macros", "uuid"] }
utoipa-swagger-ui = { workspace = true, optional = true, features = ["axum"] }
