// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: "http://localhost:4724" | (string & {});
};

export type NodeObject = {
  /**
   * Client's IP Address
   */
  clientIp: string;
  /**
   * Installation path of the node
   */
  installPath: string;
  /**
   * Node's Local IP Address
   */
  localIp: string;
  /**
   * WebSocket Address
   */
  webSocketAddr: string;
};

export type NodeInfoData = {
  body?: never;
  path?: never;
  query?: never;
  url: "api/v0/node";
};

export type NodeInfoErrors = {
  /**
   * Internal server error
   */
  500: unknown;
};

export type NodeInfoResponses = {
  /**
   * Info retrieved successfully
   */
  200: unknown;
};

export type UserRegisterData = {
  body?: never;
  path?: never;
  query?: never;
  url: "api/v0/user";
};

export type UserRegisterErrors = {
  /**
   * Internal server error
   */
  500: unknown;
};

export type UserRegisterResponses = {
  /**
   * User registered successfully
   */
  201: unknown;
};
