// This file is auto-generated by @hey-api/openapi-ts

export const NodeObjectSchema = {
  type: "object",
  required: ["install_path", "client_ip", "local_ip", "web_socket_addr"],
  properties: {
    client_ip: {
      type: "string",
      description: "Client's IP Address",
    },
    install_path: {
      type: "string",
      description: "Installation path of the node",
    },
    local_ip: {
      type: "string",
      description: "Node's Local IP Address",
    },
    web_socket_addr: {
      type: "string",
      description: "WebSocket Address",
    },
  },
} as const;
