// This file is auto-generated by @hey-api/openapi-ts

export const NodeObjectSchema = {
  type: "object",
  required: ["installPath", "clientIp", "localIp", "webSocketAddr"],
  properties: {
    clientIp: {
      type: "string",
      description: "Client's IP Address",
    },
    installPath: {
      type: "string",
      description: "Installation path of the node",
    },
    localIp: {
      type: "string",
      description: "Node's Local IP Address",
    },
    webSocketAddr: {
      type: "string",
      description: "WebSocket Address",
    },
  },
} as const;
