// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from "./client";
import { client } from "./client.gen";
import type {
  NodeInfoData,
  NodeInfoErrors,
  NodeInfoResponses,
  UserRegisterData,
  UserRegisterErrors,
  UserRegisterResponses,
} from "./types.gen";

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
> = Options2<TData, ThrowOnError> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>;
};

export const nodeInfo = <ThrowOnError extends boolean = false>(
  options?: Options<NodeInfoData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    NodeInfoResponses,
    NodeInfoErrors,
    ThrowOnError
  >({
    url: "api/v0/node",
    ...options,
  });
};

export const userRegister = <ThrowOnError extends boolean = false>(
  options?: Options<UserRegisterData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    UserRegisterResponses,
    UserRegisterErrors,
    ThrowOnError
  >({
    url: "api/v0/user",
    ...options,
  });
};
